services:
  - type: web
    name: cartit-website
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    headers:
      - path: /cartit-release.apk
        name: Content-Type
        value: application/vnd.android.package-archive
      - path: /cartit-release.apk
        name: Content-Disposition
        value: attachment; filename="CartIT-App.apk"
      - path: /cartit-delivery-release.apk
        name: Content-Type
        value: application/vnd.android.package-archive
      - path: /cartit-delivery-release.apk
        name: Content-Disposition
        value: attachment; filename="CartIT-Delivery-App.apk"
      - path: /*.apk
        name: Content-Type
        value: application/vnd.android.package-archive
      - path: /*.apk
        name: Content-Disposition
        value: attachment
    routes:
      - type: rewrite
        source: /((?!.*\.apk|.*\.png|.*\.jpg|.*\.svg|.*\.js|.*\.css).*)
        destination: /index.html
